# Generated by Django 4.2 on 2026-07-18 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=reports.models._default_unique_id, max_length=64, unique=True)),
                ('dc_number', models.CharField(max_length=64, unique=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('challan_date', models.DateField()),
                ('po_ref', models.CharField(blank=True, default='', max_length=255)),
                ('challan_type', models.CharField(default='Supply of Goods', max_length=64)),
                ('bill_to_company', models.CharField(max_length=255)),
                ('bill_to_address', models.CharField(blank=True, default='', max_length=1024)),
                ('bill_to_gst', models.CharField(blank=True, default='', max_length=32)),
                ('tax_rate', models.FloatField(default=18)),
                ('grand_total', models.FloatField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'dc',
            },
        ),
        migrations.CreateModel(
            name='Logsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=reports.models._default_unique_id, max_length=64, unique=True)),
                ('entry_date', models.DateField()),
                ('remarks', models.CharField(blank=True, default='', max_length=1024)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'logsheet',
            },
        ),
        migrations.CreateModel(
            name='Measurable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=reports.models._default_unique_id, max_length=64, unique=True)),
                ('entry_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('temp', models.FloatField()),
                ('humi', models.FloatField()),
                ('remarks', models.CharField(blank=True, default='', max_length=1024)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'measurable',
            },
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=reports.models._default_unique_id, max_length=64, unique=True)),
                ('ticket_no', models.CharField(max_length=64, unique=True)),
                ('serial_no', models.CharField(blank=True, default='', max_length=64)),
                ('vehicle_no', models.CharField(max_length=64)),
                ('vendor', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, default='', max_length=32)),
                ('empty_weight', models.FloatField(default=0)),
                ('loaded_weight', models.FloatField(default=0)),
                ('net_weight', models.FloatField(default=0)),
                ('empty_weight_date', models.DateField(blank=True, null=True)),
                ('empty_weight_time', models.CharField(blank=True, default='', max_length=32)),
                ('load_weight_date', models.DateField(blank=True, null=True)),
                ('load_weight_time', models.CharField(blank=True, default='', max_length=32)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reject',
            },
        ),
        migrations.CreateModel(
            name='RejectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=reports.models._default_unique_id, max_length=64, unique=True)),
                ('ticket_no', models.CharField(max_length=64)),
                ('image_path', models.CharField(blank=True, default='', max_length=1024)),
                ('upload_date', models.DateField()),
                ('weigh_date', models.DateField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=64)),
                ('net_weight', models.FloatField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reject_image',
            },
        ),
        migrations.CreateModel(
            name='DCItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('hsn', models.CharField(blank=True, default='', max_length=64)),
                ('qty', models.FloatField(default=0)),
                ('unit', models.CharField(default='Kgs', max_length=32)),
                ('rate', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('dc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.dc')),
            ],
            options={
                'db_table': 'dc_item',
            },
        ),
    ]
