# Generated by Django 4.2 on 2026-07-18 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import process.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CullingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=process.models._default_unique_id, max_length=64, unique=True)),
                ('entry_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('1', 'Day'), ('2', 'Night'), ('3', 'General')], max_length=32)),
                ('cylinder_type', models.CharField(choices=[('1', 'O2'), ('2', 'LPG'), ('3', 'Other')], max_length=32)),
                ('cylinder_no', models.CharField(max_length=255)),
                ('starting_weight', models.FloatField()),
                ('ending_weight', models.FloatField()),
                ('fuel_consumption', models.FloatField(default=0)),
                ('raw_material_weight', models.FloatField()),
                ('final_larvae_weight', models.FloatField()),
                ('work_done', models.CharField(choices=[('1', 'Cutting'), ('2', 'Heating'), ('3', 'Others')], max_length=32)),
                ('others_remarks', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DryProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=process.models._default_unique_id, max_length=64, unique=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('1', 'In'), ('2', 'Out')], max_length=32)),
                ('drying_method', models.CharField(choices=[('1', 'Solar'), ('2', 'Electric')], max_length=32)),
                ('quantity', models.FloatField()),
                ('qty_manure', models.FloatField(default=0)),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EggProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=process.models._default_unique_id, max_length=64, unique=True)),
                ('entry_date', models.DateField()),
                ('entry_no', models.CharField(max_length=64, unique=True)),
                ('tot_qty', models.FloatField()),
                ('tray_utilized', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EggProcessAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrpStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=process.models._default_unique_id, max_length=64, unique=True)),
                ('entry_no', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('entry_date', models.DateField()),
                ('day', models.IntegerField()),
                ('hatching_status', models.CharField(choices=[('pending', 'Pending'), ('progressing', 'Progressing'), ('completed', 'Completed')], default='pending', max_length=32)),
                ('remarks', models.TextField(blank=True, default='')),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FrpTrayProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=process.models._default_unique_id, max_length=64, unique=True)),
                ('entry_date', models.DateField()),
                ('frp_tray_count', models.IntegerField()),
                ('batch_status', models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process')], default='pending', max_length=32)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Leachate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=process.models._default_unique_id, max_length=64, unique=True)),
                ('entry_date', models.DateField()),
                ('qty_leachate', models.FloatField()),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=process.models._default_unique_id, max_length=64, unique=True)),
                ('date', models.DateField()),
                ('qty', models.FloatField()),
                ('invoice_no', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('batch_id', models.CharField(max_length=64, unique=True)),
                ('batch_status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('closed', 'Closed')], default='pending', max_length=32)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OvenProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=process.models._default_unique_id, max_length=64, unique=True)),
                ('entry_date', models.DateField()),
                ('starting_time', models.CharField(max_length=8)),
                ('closing_time', models.CharField(max_length=8)),
                ('running_hours', models.FloatField(default=0)),
                ('diesel_topup', models.FloatField()),
                ('raw_larvae_process', models.FloatField()),
                ('dried_larvae_production', models.FloatField()),
                ('dried_larvae_stock', models.FloatField()),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=process.models._default_unique_id, max_length=64, unique=True)),
                ('entry_date', models.DateField()),
                ('day', models.IntegerField()),
                ('hatching_status', models.CharField(choices=[('pending', 'Pending'), ('progressing', 'Progressing'), ('completed', 'Completed')], default='pending', max_length=32)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.materialreceived')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='PitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=process.models._default_unique_id, max_length=64, unique=True)),
                ('entry_date', models.DateField()),
                ('org_status', models.CharField(choices=[('1', 'Organic Waste Added'), ('2', 'Baby Larvae Added'), ('3', 'Aeration Process'), ('4', 'Measurement'), ('5', 'Harvest'), ('6', 'Vibro Screen'), ('7', 'Tippi')], max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('form_batch_id', models.CharField(max_length=64, unique=True)),
                ('feed_qty', models.FloatField(blank=True, null=True)),
                ('feed_count', models.IntegerField(blank=True, null=True)),
                ('larvae_qty_in', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, default='', max_length=255)),
                ('measure_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=32, null=True)),
                ('temp_start', models.FloatField(blank=True, null=True)),
                ('temp_mid', models.FloatField(blank=True, null=True)),
                ('temp_end', models.FloatField(blank=True, null=True)),
                ('humi_start', models.FloatField(blank=True, null=True)),
                ('humi_mid', models.FloatField(blank=True, null=True)),
                ('humi_end', models.FloatField(blank=True, null=True)),
                ('larvae_qty', models.FloatField(blank=True, null=True)),
                ('qty_manure_1', models.FloatField(blank=True, null=True)),
                ('qty_manure_2', models.FloatField(blank=True, null=True)),
                ('qty_manure_3', models.FloatField(blank=True, null=True)),
                ('qty_rejets', models.FloatField(blank=True, null=True)),
                ('harvest_comp', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=32, null=True)),
                ('tippi_qty', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='process.materialreceived')),
                ('pit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.pit')),
                ('trays', models.ManyToManyField(blank=True, to='inventory.tray')),
            ],
        ),
        migrations.AddIndex(
            model_name='ovenprocess',
            index=models.Index(fields=['unique_id'], name='process_ove_unique__827d48_idx'),
        ),
        migrations.AddIndex(
            model_name='ovenprocess',
            index=models.Index(fields=['-created_at'], name='process_ove_created_8dabef_idx'),
        ),
        migrations.AddConstraint(
            model_name='ovenprocess',
            constraint=models.UniqueConstraint(fields=('entry_date', 'starting_time'), name='ovenprocess_unique_entry_date_starting_time'),
        ),
        migrations.AddField(
            model_name='materialreceived',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='materialreceived',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='materialreceived',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unit'),
        ),
        migrations.AddIndex(
            model_name='leachate',
            index=models.Index(fields=['unique_id'], name='process_lea_unique__8d9a92_idx'),
        ),
        migrations.AddIndex(
            model_name='leachate',
            index=models.Index(fields=['-created_at'], name='process_lea_created_d6daa1_idx'),
        ),
        migrations.AddField(
            model_name='frptrayprocess',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.materialreceived', unique=True),
        ),
        migrations.AddField(
            model_name='frptrayprocess',
            name='trays',
            field=models.ManyToManyField(blank=True, to='inventory.tray'),
        ),
        migrations.AddField(
            model_name='frpstatusupdate',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.frptrayprocess'),
        ),
        migrations.AddField(
            model_name='frpstatusupdate',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='eggprocessaddon',
            name='egg_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='process.eggprocess'),
        ),
        migrations.AddField(
            model_name='eggprocessaddon',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='eggprocess',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.materialreceived'),
        ),
        migrations.AddField(
            model_name='eggprocess',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='eggprocess',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='eggprocess',
            name='trays',
            field=models.ManyToManyField(blank=True, to='inventory.tray'),
        ),
        migrations.AddIndex(
            model_name='dryprocess',
            index=models.Index(fields=['unique_id'], name='process_dry_unique__fe16e3_idx'),
        ),
        migrations.AddIndex(
            model_name='dryprocess',
            index=models.Index(fields=['-created_at'], name='process_dry_created_3d28cb_idx'),
        ),
        migrations.AddIndex(
            model_name='cullingprocess',
            index=models.Index(fields=['unique_id'], name='process_cul_unique__1fccd8_idx'),
        ),
        migrations.AddIndex(
            model_name='cullingprocess',
            index=models.Index(fields=['-created_at'], name='process_cul_created_e99784_idx'),
        ),
        migrations.AddConstraint(
            model_name='cullingprocess',
            constraint=models.UniqueConstraint(fields=('entry_date', 'shift_type', 'cylinder_no'), name='cullingprocess_unique_entry_date_shift_type_cylinder_no'),
        ),
        migrations.AddIndex(
            model_name='statusupdate',
            index=models.Index(fields=['unique_id'], name='process_sta_unique__0937c3_idx'),
        ),
        migrations.AddIndex(
            model_name='statusupdate',
            index=models.Index(fields=['-created_at'], name='process_sta_created_957517_idx'),
        ),
        migrations.AddIndex(
            model_name='pitstatus',
            index=models.Index(fields=['unique_id'], name='process_pit_unique__c98e50_idx'),
        ),
        migrations.AddIndex(
            model_name='pitstatus',
            index=models.Index(fields=['form_batch_id'], name='process_pit_form_ba_1eaf92_idx'),
        ),
        migrations.AddIndex(
            model_name='pitstatus',
            index=models.Index(fields=['pit'], name='process_pit_pit_id_bdb1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='pitstatus',
            index=models.Index(fields=['org_status'], name='process_pit_org_sta_dfa698_idx'),
        ),
        migrations.AddIndex(
            model_name='pitstatus',
            index=models.Index(fields=['-created_at'], name='process_pit_created_4e60ae_idx'),
        ),
        migrations.AddIndex(
            model_name='materialreceived',
            index=models.Index(fields=['unique_id'], name='process_mat_unique__aa0136_idx'),
        ),
        migrations.AddIndex(
            model_name='materialreceived',
            index=models.Index(fields=['-created_at'], name='process_mat_created_7ee591_idx'),
        ),
        migrations.AddIndex(
            model_name='frptrayprocess',
            index=models.Index(fields=['unique_id'], name='process_frp_unique__92beaa_idx'),
        ),
        migrations.AddIndex(
            model_name='frptrayprocess',
            index=models.Index(fields=['-created_at'], name='process_frp_created_838f76_idx'),
        ),
        migrations.AddIndex(
            model_name='frpstatusupdate',
            index=models.Index(fields=['unique_id'], name='process_frp_unique__a7adfb_idx'),
        ),
        migrations.AddIndex(
            model_name='frpstatusupdate',
            index=models.Index(fields=['entry_no'], name='process_frp_entry_n_00a52a_idx'),
        ),
        migrations.AddIndex(
            model_name='frpstatusupdate',
            index=models.Index(fields=['-created_at'], name='process_frp_created_5cbd7a_idx'),
        ),
        migrations.AddIndex(
            model_name='eggprocess',
            index=models.Index(fields=['unique_id'], name='process_egg_unique__1ad445_idx'),
        ),
        migrations.AddIndex(
            model_name='eggprocess',
            index=models.Index(fields=['entry_no'], name='process_egg_entry_n_7c23c2_idx'),
        ),
        migrations.AddIndex(
            model_name='eggprocess',
            index=models.Index(fields=['-created_at'], name='process_egg_created_0d72b7_idx'),
        ),
    ]
