# Generated by Django 4.2 on 2026-07-18 06:06

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=core.models._default_unique_id, max_length=64, unique=True)),
                ('screen_main_name', models.CharField(max_length=255)),
                ('screen_type', models.CharField(blank=True, default='', max_length=64)),
                ('icon_name', models.CharField(blank=True, default='', max_length=128)),
                ('order_no', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'main_screens',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=core.models._default_unique_id, max_length=64, unique=True)),
                ('screen_name', models.CharField(max_length=255)),
                ('folder_name', models.CharField(max_length=255)),
                ('icon_name', models.CharField(blank=True, default='', max_length=128)),
                ('order_no', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('actions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('main_screen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mainscreen')),
            ],
            options={
                'db_table': 'screens',
            },
        ),
    ]
